name: Docker Build and Push

on:
  push:
    branches:
      - main
      - mooon

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend Docker image
        id: build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Build and push Product Catalog Service Docker image
        id: build_productcatalogservice
        uses: docker/build-push-action@v2
        with:
          context: ./productcatalogservice
          file: ./productcatalogservice/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/productcatalogservice:latest

      - name: Checkout microservices-repo
        uses: actions/checkout@v2
        with:
          repository: KSEUNGJ/microservices-repo
          ref: mooon
          token: ${{ secrets.GIT_REPO_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update productcatalogservice.yaml and commit changes
        run: |
          sed -i 's|image:.*|image: '"${{ secrets.DOCKER_USERNAME }}"'/productcatalogservice:latest|g' kustomize/base/productcatalogservice.yaml
          if grep -q "# Last updated at" kustomize/base/productcatalogservice.yaml; then
            sed -i 's|# Last updated at.*|# Last updated at $(date)|' kustomize/base/productcatalogservice.yaml
          else
            echo "# Last updated at $(date)" >> kustomize/base/productcatalogservice.yaml
          fi
          git add kustomize/base/productcatalogservice.yaml
          git commit -m "Update productcatalogservice image to latest" --allow-empty

      - name: Update frontend.yaml and commit changes
        run: |
          sed -i 's|image:.*|image: '"${{ secrets.DOCKER_USERNAME }}"'/frontend:latest|g' kustomize/base/frontend.yaml
          if grep -q "# Last updated at" kustomize/base/frontend.yaml; then
            sed -i 's|# Last updated at.*|# Last updated at $(date)|' kustomize/base/frontend.yaml
          else
            echo "# Last updated at $(date)" >> kustomize/base/frontend.yaml
          fi
          git add kustomize/base/frontend.yaml
          git commit -m "Update frontend image to latest" --allow-empty

      - name: Push changes
        run: |
          git push origin mooon
        env:
          GIT_REPO_TOKEN: ${{ secrets.GIT_REPO_TOKEN }}
