name: Docker Build and Push

on:
  push:
    branches:
      - main
      - mooon

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout microservices-repo
        uses: actions/checkout@v2
        with:
          repository: KSEUNGJ/microservices-repo
          ref: mooon
          token: ${{ secrets.GIT_REPO_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update YAML files and commit changes
        run: |
          sed -i 's|image:.*productcatalogservice:.*|image: '"${{ secrets.DOCKER_USERNAME }}"'/productcatalogservice:latest|g' kustomize/base/productcatalogservice.yaml
          git add kustomize/base/productcatalogservice.yaml
          git commit -m "Update productcatalogservice image to latest" --allow-empty
          sed -i 's|image:.*frontend:.*|image: '"${{ secrets.DOCKER_USERNAME }}"'/frontend:latest|g' kustomize/base/frontend.yaml
          git add kustomize/base/frontend.yaml
          git commit -m "Update frontend image to latest" --allow-empty
          git push origin mooon
