name: Build, Push Docker Images and Update YAML

on:
  push:
    branches:
      - main

jobs:
  build-push-update:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend Docker image
        id: build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Build and push Product Catalog Service Docker image
        id: build_productcatalogservice
        uses: docker/build-push-action@v2
        with:
          context: ./productcatalogservice
          file: ./productcatalogservice/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/productcatalogservice:latest

      - name: Checkout microservices-repo
        uses: actions/checkout@v2
        with:
          repository: KSEUNGJ/microservices-repo
          ref: mooon
          token: ${{ secrets.GIT_REPO_TOKEN }}
          fetch-depth: 0

      - name: Update productcatalogservice.yaml
        run: |
          sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/productcatalogservice:latest|g' kustomize/base/productcatalogservice.yaml
          touch kustomize/base/productcatalogservice.yaml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add kustomize/base/productcatalogservice.yaml
          git commit -m "Update productcatalogservice image to latest" --allow-empty
          git push origin mooon

      - name: Update frontend.yaml
        run: |
          sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/frontend:latest|g' kustomize/base/frontend.yaml
          touch kustomize/base/frontend.yaml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add kustomize/base/frontend.yaml
          git commit -m "Update frontend image to latest" --allow-empty
          git push origin mooon

      - name: Push changes
        run: |
          git push origin mooon
        env:
          GIT_REPO_TOKEN: ${{ secrets.GIT_REPO_TOKEN }}
